name: Build development
jobs:
  android_development_build:
    name: Build Android
    type: build
    params:
      platform: android
      profile: development
# Tämä workflow rakentaa kehitysprototyypin sovelluksesta, jossa on käytössä kehitystyökalut.
# Workflowin voi ajaa manuaalisesti komennolla 'eas workflow:run .eas\workflows\build-development.yml'