name: Build production
jobs:
  android_development_build:
    name: Build Android
    type: build
    params:
      platform: android
      profile: production
# Tämä Workflow rakentaa tuotantoproton sovelluksesta. Ota huomioon että tuotantoproton voi asentaa vain kaupasta.
# Workflowin voi ajaa manuaalisesti komennolla 'eas workflow:run .eas\workflows\build-production.yml'