name: Build preview
jobs:
  android_development_build:
    name: Build Android
    type: build
    params:
      platform: android
      profile: preview
# Tämä workflow rakentaa esikatseluprototyypin sovelluksesta. Se ei sisällä kehitystyökaluja, mutta sopii tuotannon esikatseluun.
# Workflowin voi ajaa manuaalisesti komennolla 'eas workflow:run .eas\workflows\build-preview.yml'