name: Create development builds

  # Ajamalla eas workflow:run *insert tämän tiedoston polku* voidaan tehdä development buildi

jobs:
  android_development_build:
    name: Build Android
    type: build
    params:
      platform: android
      profile: development
