name: Publish preview update
  # This workflow publishes a preview update to Expo for the team to test without needing to build in IDE
on:
  push:
    branches: ['*']
  # Generates a preview update on every push.
jobs:
  publish_preview_update:
    name: Publish preview update
    type: update
    params:
      branch: ${{ github.ref || 'test' }}